### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sumeetjain** [Ayolland/2015-02-11-web-warehouse#1]
Really happy with this overall. Great modularity and creativity. Some feedback:

---

Indentation

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/views/view_all.erb#L4-L5

No need to fix immediately.

---

ERB should be one line of code per tag.

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/views/del.erb#L1-L2

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/views/del.erb#L5-L7

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/views/del.erb#L8-L12

No need to fix immediately.

---

If possible, ruby logic and variable assignment should reside in the route handler.

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/views/del.erb#L1-L2

Please fix before moving on.

---

This much work should be stored in a method that can then be called from the route handler (or view, if necessary).

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/views/del.erb#L8

There's never really a reason to directly execute SQL commands via a view.

Please fix before moving on.

---

While it works, it's error prone later; so avoid the habit of leaving quotes off HTML attribute values.

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/views/del.erb#L21

No need to fix immediately.

---

Too long. Break to multiple lines and indent please.

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/views/bits/nav.erb#L1

Please fix before moving on.

---

Documentation please.

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/helpers/helpers.rb

Please fix before moving on. Just do 2 of them.

---

Valid camel-case doesn't have underscores.

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/models/modules.rb#L1

(No need to fix, just FYI.)

---

Improper spacing/indentation.

https://github.com/Ayolland/2015-02-11-web-warehouse/blob/master/models/modules.rb#L21-L41

(No need to fix. Just be careful.)

**Comment by Ayolland** [comment]
So, 2 things:

1) It's not clear to me: Fix these issue before beginning the new project?

2) Re: ERB should be one line of code per tag. 
My use of the 'pre' tag made that not feasible, since carriage returns/spaces are noted inside of that tag. I may have got confused and started condensing tags outside of that.

**Comment by sumeetjain** [comment]
Updated the issue with fix-timelines.

For 2) That's fair. No need to modify that.
